name: Maven Project Verification

on:
  push:
    branches-ignore: [ main ]
  schedule:
    - cron: '0 0 * * *'

jobs:
  build:

    name: Maven Build/Verify
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      packages: read
      security-events: write

    steps:
    - uses: actions/checkout@v3

    - name: Login to GHCR
      uses: docker/login-action@v2.0.0
      with:
        registry: ghcr.io
        username: _json_key
        password: ${{ secrets.PACKAGES_PAT }}

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'
        server-id: github
        server-username: USERNAME
        server-password: TOKEN
        settings-path: ${{ github.workspace }}

    - name: Build/Deploy with Maven
      run: |
        mvn --batch-mode --show-version --strict-checksums --fail-at-end versions:set -DgenerateBackupPoms=false -DnewVersion="${{github.run_number}}.0.${{github.run_id}}"
        mvn --batch-mode --show-version --strict-checksums --fail-at-end --settings $GITHUB_WORKSPACE/settings.xml -DaltDeploymentRepository=github::https://maven.pkg.github.com/ercot/ghas-trial -Dimage.tag=${GITHUB_SHA} package
      env:
        USERNAME: ercot
        TOKEN: ${{ secrets.PACKAGES_PAT }}

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2

    - name: Upload Dependency-Check Scan SARIF file
      uses: github/codeql-action/upload-sarif@v1
      with:
        sarif_file: target/dependency-check-report.sarif

  analyze:
    name: CodeQL Analysis
    runs-on: ubuntu-latest
    permissions:
      actions: read
      contents: read
      security-events: write

    strategy:
      fail-fast: false
      matrix:
        language: [ 'java' ]

    steps:
    - uses: actions/checkout@v3

    - name: Initialize CodeQL
      uses: github/codeql-action/init@v2
      with:
        languages: ${{ matrix.language }}
        queries: security-and-quality

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Execute Maven Build
      run: |
        mvn --batch-mode --show-version --strict-checksums --fail-at-end compile

    - name: Perform CodeQL Analysis
      uses: github/codeql-action/analyze@v2
